---
- name: Install redis
  yum:
    name: redis
    enablerepo: remi
    state: latest

- name: Make sure redis is started and enabled
  service:
    name: redis
    state: started
    enabled: yes

- name: Copy redis connection conf file for rspamd
  copy:
    src: redis.conf
    dest: /etc/rspamd/local.d/redis.conf
    mode: 0644
  notify: restart rspamd
