---
- name: Install redis
  apt:
    name: redis
    state: latest

- name: Make sure redis is started and enabled
  service:
    name: redis
    state: started
    enabled: yes

- name: Copy redis connection conf file for rspamd
  copy:
    src: redis.conf
    dest: /etc/rspamd/local.d/redis.conf
    mode: 0640
  notify: restart rspamd
