---
- name: install php-fpm
  apt:
    name: php{{ php_version_u }}-fpm
    state: latest

- name: install php modules
  apt:
    name: "{{ php_modules_u }}"
    state: latest
  notify: restart debian php-fpm

- name: clear default pool file
  copy:
    content: '; disabled, use separate vhost pools'
    dest: /etc/php/{{ php_version_u }}/fpm/pool.d/www.conf
  notify: restart debian php-fpm

- name: create pool for a virtual host
  template:
    dest: /etc/php/{{ php_version_u }}/fpm/pool.d/{{ vhost }}.conf
    src: vhost_pool_debian.j2
  notify: restart debian php-fpm

- name: change upload size vars in php.ini
  ini_file:
    path: /etc/php/{{ php_version_u }}/fpm/php.ini
    section: PHP
    option: "{{ item.options }}"
    value: "{{ item.value }}"
  loop:
    - { options: 'post_max_size', value: '64M' }
    - { options: 'upload_max_filesize', value: '64M' }
    - { options: 'short_open_tag', value: 'On' }
    - { options: 'cgi.fix_pathinfo', value: '0' }
    - { options: 'date.timezone', value: 'Asia/Almaty' }
  notify: restart debian php-fpm

- name: Create /var/www/ vhost subdir
  file:
    state: directory
    path: /var/www/{{ vhost }}/
    owner: www-data
    group: www-data
    mode: 0755

- name: copy index file into virtualhost root
  copy:
    src: index.php
    dest: /var/www/{{ vhost }}/index.php
    owner: www-data
    group: www-data
    mode: 0644

- name: add fpm handler block for nginx
  blockinfile:
    marker: ' '
    path: /etc/nginx/vhosts/{{ vhost }}.conf
    insertafter: '## handler ##'
    block: |
      location ~ \.php$ {
              fastcgi_index index.php;
              fastcgi_param PHP_ADMIN_VALUE "sendmail_path = /usr/sbin/sendmail -t -i -f webmaster@{{ vhost }}";
              fastcgi_pass unix:/var/run/php/{{ vhost }}.sock;
              fastcgi_split_path_info ^((?U).+\.ph(?:p\d*|tml))(/?.+)$;
              try_files $uri =404;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;

              fastcgi_read_timeout 300;
              fastcgi_busy_buffers_size 16k;
              fastcgi_buffers 32 16k;
      }
  notify: restart nginx

- name: ensure fpm is started and enabled
  service:
    name: php{{ php_version_u }}-fpm
    enabled: yes
    state: started
