---
- name: restart debian php-fpm
  service:
    name: php{{ php_version_u }}-fpm
    state: restarted

- name: restart centos php-fpm
  service:
    name: php{{ php_version }}-php-fpm
    state: restarted
