---
- name: install packages
  apt:
    name: "{{ main_packages }}"
    update_cache: yes
  vars:
    main_packages:
      - dovecot-lmtpd
      - dovecot-mysql
      - dovecot-imapd
      - dovecot-pop3d

- name: copy 10-mail
  copy:
    src: 10-mail.conf
    dest: /etc/dovecot/conf.d/10-mail.conf
    mode: 0644
  notify: restart dovecot

- name: copy 10-auth
  copy:
    src: 10-auth.conf
    dest: /etc/dovecot/conf.d/10-auth.conf
    mode: 0644
  notify: restart dovecot

- name: copy 10-ssl
  template:
    src: 10-ssl.conf
    dest: /etc/dovecot/conf.d/10-ssl.conf
    mode: 0644
  notify: restart dovecot

- name: copy dovecot-sql
  copy:
    src: dovecot-sql.conf.ext
    dest: /etc/dovecot/dovecot-sql.conf.ext
    mode: 0644
  notify: restart dovecot

- name: replace dummy password in dovecot-sql
  replace:
    path: /etc/dovecot/dovecot-sql.conf.ext
    regexp: 'strong_password$'
    replace: "{{ file_contents }}"
  vars:
    file_contents: "{{ lookup('file', '/root/060-pfxadmin_db_password') }}"
  notify: restart dovecot

- name: enable ssl support
  lineinfile:
    regexp: '^ssl'
    line: 'ssl = yes'
    path: /etc/dovecot/conf.d/10-ssl.conf
  notify: restart dovecot

- name: set postmaster email address
  lineinfile:
    regexp: '^postmaster_address'
    line: 'postmaster_address = postmaster@{{ vhost }}'
    path: /etc/dovecot/conf.d/15-lda.conf
  notify: restart dovecot

- name: copy 10-master
  copy:
    src: 10-master.conf
    dest: /etc/dovecot/conf.d/10-master.conf
    mode: 0644
  notify: restart dovecot

- name: create vmail group
  group:
    name: vmail
    gid: 150
    state: present

- name: create vmail user
  user:
    name: vmail
    uid: 150
    group: vmail
    shell: /bin/nologin

- name: create /var/vmail directory
  file:
    path: /var/vmail
    state: directory
    owner: vmail
    group: mail

- name: change dovecot directory permissions
  file:
    path: /etc/dovecot/
    state: directory
    owner: vmail
    group: dovecot
    mode: 0750

- name: make sure dovecot is enabled
  service:
    name: dovecot
    enabled: yes

- name: enable  pop and imap on ufw
  ufw:
    state: enabled
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - pop3
    - pop3s
    - imap
    - imaps
